# Updated Dockerfile with additional OpenGL libraries and environment variables

FROM some/base_image

# Existing APT commands
RUN apt-get update && apt-get install -y \
  ... \
  libglu1-mesa-dev \
  libglu1-mesa \
  libxrandr-dev \
  libxinerama-dev \
  libxcursor-dev \
  libxi-dev \
  libxext-dev \
  libxrender-dev \
  ...

# Set OpenGL environment variables
ENV OPENGL_gl_LIBRARY=/usr/lib/x86_64-linux-gnu/libGL.so.1 \
    OPENGL_glu_LIBRARY=/usr/lib/x86_64-linux-gnu/libGLU.so.1 \
    OPENGL_INCLUDE_DIR=/usr/include \
    OpenGL_GL_PREFERENCE=GLVND \
    PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig:/usr/local/lib/pkgconfig

# Compilation step
RUN make release-static
